/*
 * This source file was generated by the Gradle 'init' task
 */
package jpt;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void testDemoProcess() {
        try {
            Jprocess.demoProcess();
        } catch (Exception e) {
            e.printStackTrace();
            fail("Exception thrown during Jprocess.demoProcess()");
        }
    }

    @Test
    void testGetCurrentProcessInfo() {
        Jprocess.getCurrentProcessInfo();
        // Since this method prints to console, we can't assert its output easily.
        // We just ensure it runs without throwing exceptions.  
    }

}
